export { default as Login } from "./Login";
export { default as Dashboard } from "./Dashboard";
export { default as Errors } from "./Errors";
export { default as Register } from "./Register";
export { default as DashboardLayout } from "./DashboardLayout";
export { default as ProductLayout } from "./ProductLayout";
export { default as TestApp } from "./testApp";
export { default as ProfilePage } from "./ProfilePage";
export { default as AddProductForm } from "./AddProductForm";
export { default as Check } from "./Check";
export { default as AddCategory } from "./AddCategory";
export { default as PermissionsManager } from "./PermissionsManager";
export { default as Users } from "./Users";

export { default as Permissions } from "./Permissions";
export { default as Screens } from "./Screens";
export { default as Products } from "./Products";
export { default as Categories } from "./Categories";
export { default as Promotionals } from "./Promotionals";
